#pragma once
#include <cstdint>

struct Block{
    enum {
        air = 0,
        dirt,
        grassBlock,
        stone,
        grass,
        sand,
        sandRuby,
        SandStone,
        woodPLank,
        stoneBricks,
        clay,
        woodLog,
        leaves,
        copper,
        iron,
        gold,
        copperBlock,
        ironBlock,
        goldBlock,
        bricks,
        snow,
        ice,
        rubyBlock,
        platform,
        workBench,
        glass,
        furnace,
        painting,
        sappling,
        snowBlueRuby,
        door,
        jar,
        table,
        wordrobe,
        bookShelf,
        snowBricks,
        iceTable,
        iceWordrobe,
        iceBookShelf,
        icePlatform,
        sandTable,
        sandWordrobe,
        sandBookShelf,
        sandPlatform,
        woodenChest,
        iceChest,
        sandChest,
        boneChest,
        boneBricks,
        boneBench,
        boneWordrobe,
        boneBookShelf,
        bonePlatform,

        BLOCKS_COUNT,
    };
    std::uint16_t type = 0;
};

inline constexpr const char* blockNames[] = {
    "air", "dirt", "grassBlock", "stone", "grass", "sand", "sandRuby", "SandStone",
    "woodPLank", "stoneBricks", "clay", "woodLog", "leaves", "copper", "iron", "gold",
    "copperBlock", "ironBlock", "goldBlock", "bricks", "snow", "ice", "rubyBlock",
    "platform", "workBench", "glass", "furnace", "painting", "sappling", "snowBlueRuby",
    "door", "jar", "table", "wordrobe", "bookShelf", "snowBricks", "iceTable",
    "iceWordrobe", "iceBookShelf", "icePlatform", "sandTable", "sandWordrobe",
    "sandBookShelf", "sandPlatform", "woodenChest", "iceChest", "sandChest",
    "boneChest", "boneBricks", "boneBench", "boneWordrobe", "boneBookShelf",
    "bonePlatform",
};

static_assert(sizeof(blockNames) / sizeof(blockNames[0]) == Block::BLOCKS_COUNT,
              "blockNames must have one name for every block type");
